### ISSUE TITLE
请问下是不是只是支持采集node-exporter，但是不支持复杂计算类似rate()

### ISSUE THREAD

**Issue by feixia5712** [n9e/prometheus-exporter-collector#16]

**Comment by lts120784620** [comment]
支持接入符合prometheus指标体系的各种exporter，默认会跟据配置"default_mapping_metric_type"将promehtheus中计数器类型指标转为差值或者速率

**Comment by feixia5712** [comment]
搜集上来的counter是转过之后的吗

**Comment by lts120784620** [comment]
是的，对prom中counter、Summary，Histogram中的sum/count会根据default_mapping_metric_type转换类型，其他作为gauge上报到夜莺agent，夜莺agent会对counter类型做速率转换
