### ISSUE TITLE
parse metrics result error: json: unsupported value: NaN

### ISSUE THREAD

**Issue by sheeplinjie** [n9e/prometheus-exporter-collector#22]
parse metrics result error: json: unsupported value: NaN
What's the problem？

**Comment by chenzhcnj** [comment]
同样的问题

**Comment by UlricQin** [comment]
用master手工编辑最新版本的代码，应该就好了

**Comment by David0653116** [comment]
用master代码手动编译（go1.17.7），好像还是同样的问题。
报错：
parse metrics result error: json: unsupported value: -Inf
