### ISSUE TITLE
你好这样配置为啥采集不到数据，但是手动测试是可以的

### ISSUE THREAD

**Issue by feixia5712** [n9e/prometheus-exporter-collector#24]
夜莺版本2.x
在server端配置如下
![image](https://user-images.githubusercontent.com/12670758/121321157-700e3000-c940-11eb-8107-d673a1033920.png)
在客户端测试是正常的
![image](https://user-images.githubusercontent.com/12670758/121321290-8b793b00-c940-11eb-93c9-cefb8c57b196.png)
![image](https://user-images.githubusercontent.com/12670758/121321334-9633d000-c940-11eb-9797-55e3b215ea3a.png)
但是在服务端看不到任何数据
![image](https://user-images.githubusercontent.com/12670758/121321531-c2e7e780-c940-11eb-88db-92ad35367153.png)
我前几个月还试过是可以的，今天打算使用，不行了

**Comment by feixia5712** [comment]
请教下有什么排查思路吗，看了看collector没啥错误日志

**Comment by UlricQin** [comment]
升级到v3.8试试
