### ISSUE TITLE
parse metrics result error: json: unsupported value: +Inf

### ISSUE THREAD

**Issue by yangjiahui417** [n9e/prometheus-exporter-collector#27]
I want to use n9e to monitor TiDB，but the prometheus-exporter-collector plugin can't parse TiFlash metrics,see error log in the follow 
`less /data/n9e/logs/agentd/ERROR.log`
`ERROR plugins/scheduler.go:111 exec /data/n9e/plugins/prometheus-exporter-collector fail: 2021/10/20 16:02:33 parse metrics result error: json: unsupported value: +Inf`

` curl http://127.0.0.1:8234/metrics|grep +Inf`
`tiflash_storage_logical_throughput_bytes_sum{type="read"} +Inf`

the `+inf` is out of the json format,so the prometheus-exporter-collector plugin can't parse  the other metrics,how to resove this problem?

**Comment by UlricQin** [comment]
ignore the +Inf values. prometheus-exporter-collector only supports float64.
