### ISSUE TITLE
请问具体一点的过程是什么？通过Nightingale插件采集，collector采集目标exporter指标并上报

### ISSUE THREAD

**Issue by a1340080222** [n9e/prometheus-exporter-collector#29]
希望实现监控mysql的相关数据 请问具体一点操作过程是什么？
目前理解是使用prometheus-exporter-collector去读pormethues mysqld_exporter提供的数据并发送给agentd，agentd在发送给server
但是不知道如何查看效果

![image](https://user-images.githubusercontent.com/61442052/144202792-71d4679c-e21f-4784-a332-2ebd13ba1763.png)

下面是prometheus-exporter-collector的路径，安装在想要监控的虚拟机上，已运行mysql，agentd
![image](https://user-images.githubusercontent.com/61442052/144203366-0899af22-79c3-479a-a763-2bb731ea30a3.png)
![image](https://user-images.githubusercontent.com/61442052/144204539-88834e87-1655-4840-87b4-83c2de95c05f.png)

server的web上应该怎么设置？
![image](https://user-images.githubusercontent.com/61442052/144204757-dd7cb32d-021e-42ee-a59e-3da0a3b0c176.png)

**Comment by UlricQin** [comment]
v5版本无需prometheus-exporter-collector，直接在prometheus.yml中配置scrape规则就行了。另外正式版下周发布，可以稍等再测
