### ISSUE TITLE
第三方多平台接入prometheus-exporter报路径错误

### ISSUE THREAD

**Issue by nondevops** [n9e/prometheus-exporter-collector#6]
我分别在阿里云和UCLOUD的实例都部署了promethus-exporter和 redis_exporter ,当这俩机器的服务(promethus-exporter和 redis_exporter) 同时工作时,就会互相报找不到执行路径,如果采集器只留一个,则不会有这个问题。

监控系统的采集截图：
![image](https://user-images.githubusercontent.com/12181410/85382326-6e056280-b571-11ea-9766-f1b7c31983b0.png)

阿里云实例的报错日志：
![image](https://user-images.githubusercontent.com/12181410/85382338-71005300-b571-11ea-88c7-bb60bb59038f.png)

ucloud实例的报错日志：
![image](https://user-images.githubusercontent.com/12181410/85382352-7493da00-b571-11ea-91a2-07fb158f00a9.png)

监控系统采集ucloud实例的采集配置：
![image](https://user-images.githubusercontent.com/12181410/85382380-7b225180-b571-11ea-8768-9a207bc58a98.png)

监控系统采集aliyun实例的采集配置：
![image](https://user-images.githubusercontent.com/12181410/85382413-837a8c80-b571-11ea-9c30-313ee1735b14.png)

ucloud实例上的prometheus-exporter命令的执行路径
![image](https://user-images.githubusercontent.com/12181410/85398261-8aac9500-b587-11ea-8da1-b3731776b2e8.png)

aliyun实例上的prometheus-exporter命令的执行路径
![image](https://user-images.githubusercontent.com/12181410/85398364-b0d23500-b587-11ea-8d60-480d86fd4446.png)

**Comment by nondevops** [comment]
这是ucloud实例上的prometheus-exporter命令的执行路径
![image](https://user-images.githubusercontent.com/12181410/85398261-8aac9500-b587-11ea-8da1-b3731776b2e8.png)
-------------
这是aliyun实例上的prometheus-exporter命令的执行路径
![image](https://user-images.githubusercontent.com/12181410/85398364-b0d23500-b587-11ea-8d60-480d86fd4446.png)

**Comment by UlricQin** [comment]
这个采集策略是配置到节点上的，节点下的机器都会生效，所以两个机器都会同时去采集promethus-exporter和 redis_exporter ，而你这两个采集用到的插件路径不同，所以肯定有问题
