### ISSUE TITLE
按照相关的启动没有收集到信息

### ISSUE THREAD

**Issue by AnkerZhang** [n9e/prometheus-exporter-collector#8]
![image](https://user-images.githubusercontent.com/23515784/86700836-0b699780-c044-11ea-86c7-6cb44b3f648b.png)
![image](https://user-images.githubusercontent.com/23515784/86700962-29cf9300-c044-11ea-908e-42943bcfad6c.png)
![image](https://user-images.githubusercontent.com/23515784/86701006-3522be80-c044-11ea-932b-12e4b5892f58.png)
![image](https://user-images.githubusercontent.com/23515784/86701055-42d84400-c044-11ea-85ee-19cdeccfbfeb.png)
缺少什么配置吗  ？文件路径复制过去了一份 /root/mysqld_exporter

**Comment by UlricQin** [comment]
配置的不对，仔细看一下视频
